version: 2

jobs:

  build-9.2:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Docker image
          command: cp -R files 9.2/files
      - run:
          name: Build Docker image
          command: docker build --no-cache -t lowieh/docker-node-gcp:9.2 9.2
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push lowieh/docker-node-gcp:9.2
            fi


workflows:
  version: 2

  build:
    jobs:
      - build-9.2
